# aura_rules.conf - Cyber Aura Dynamic Rules Engine
INBOUND_LOG | UNION SELECT | BLOCK_IP_UFW
INBOUND_LOG | ../etc/passwd | BLOCK_IP_UFW
INBOUND_LOG | HACK_ATTEMPT | BLOCK_IP_UFW
FILE_MONITOR | /var/www/html/index.php | ENCRYPT_CHACHA20
FILE_MONITOR | /etc/shadow | KILL_PROCESS_PID
